#pragma once

#include "driver/gpio.h"

// I2C shared bus pins (IMU, INA226, VL53L0X)
#define I2C_SDA_PIN GPIO_NUM_21
#define I2C_SCL_PIN GPIO_NUM_22

// Motor driver + encoder pins
#define MOTOR_STBY_PIN GPIO_NUM_4
#define MOTOR_LEFT_PWM_PIN  GPIO_NUM_18
#define MOTOR_LEFT_IN1_PIN  GPIO_NUM_19
#define MOTOR_LEFT_IN2_PIN  GPIO_NUM_26
#define MOTOR_LEFT_ENC_A_PIN GPIO_NUM_32
#define MOTOR_LEFT_ENC_B_PIN GPIO_NUM_33

#define MOTOR_RIGHT_PWM_PIN  GPIO_NUM_23
#define MOTOR_RIGHT_IN1_PIN  GPIO_NUM_27
#define MOTOR_RIGHT_IN2_PIN  GPIO_NUM_16
#define MOTOR_RIGHT_ENC_A_PIN GPIO_NUM_25
#define MOTOR_RIGHT_ENC_B_PIN GPIO_NUM_17