/* ===================================================
   Script Físico — Micromouse (referência)
   As tabelas são criadas pelo SQLModel via create_all.
   Este arquivo serve como documentação e como fallback
   caso se deseje criar o schema manualmente.
   =================================================== */

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_status_corrida') THEN
        CREATE TYPE enum_status_corrida AS ENUM ('EM ANDAMENTO', 'CONCLUIDA', 'ABORTADA');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_labirinto') THEN
        CREATE TYPE enum_labirinto AS ENUM ('4X4', '8X8', '16X16');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS labirinto (
    id_labirinto INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tipo_labirinto enum_labirinto NOT NULL,
    CONSTRAINT pk_labirinto_id_labirinto PRIMARY KEY (id_labirinto)
);

CREATE TABLE IF NOT EXISTS corrida (
    id_corrida INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tempo_total INTEGER,
    tensao_media REAL,
    corrente_media REAL,
    velocidade_maxima_percurso REAL,
    velocidade_media REAL,
    status_corrida enum_status_corrida NOT NULL,
    data_hora_inicio TIMESTAMPTZ,
    data_hora_fim TIMESTAMPTZ,
    id_labirinto INTEGER,
    desafio_cumprido BOOLEAN,
    CONSTRAINT pk_corrida_id_corrida PRIMARY KEY (id_corrida),
    CONSTRAINT fk_corrida_labirinto FOREIGN KEY (id_labirinto)
        REFERENCES labirinto (id_labirinto)
);

CREATE TABLE IF NOT EXISTS celula (
    id_celula INTEGER GENERATED BY DEFAULT AS IDENTITY,
    coordenada_x INTEGER,
    coordenada_y INTEGER,
    parede_norte BOOLEAN,
    parede_sul BOOLEAN,
    parede_leste BOOLEAN,
    parede_oeste BOOLEAN,
    id_labirinto INTEGER,
    CONSTRAINT pk_celula_id_celula PRIMARY KEY (id_celula),
    CONSTRAINT fk_celula_labirinto FOREIGN KEY (id_labirinto)
        REFERENCES labirinto (id_labirinto) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS conexao_celula (
    id_celula1 INTEGER NOT NULL,
    id_celula2 INTEGER NOT NULL,
    CONSTRAINT pk_conexao_celula PRIMARY KEY (id_celula2, id_celula1),
    CONSTRAINT fk_conexao_celula_celula1 FOREIGN KEY (id_celula1)
        REFERENCES celula (id_celula) ON DELETE CASCADE,
    CONSTRAINT fk_conexao_celula_celula2 FOREIGN KEY (id_celula2)
        REFERENCES celula (id_celula) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS percurso (
    id_percurso INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_celula INTEGER,
    id_corrida INTEGER,
    data_hora_passagem TIMESTAMPTZ,
    CONSTRAINT pk_percurso_id_percurso PRIMARY KEY (id_percurso),
    CONSTRAINT fk_percurso_celula FOREIGN KEY (id_celula)
        REFERENCES celula (id_celula) ON DELETE SET NULL,
    CONSTRAINT fk_percurso_corrida FOREIGN KEY (id_corrida)
        REFERENCES corrida (id_corrida) ON DELETE SET NULL
);
