"""init - criar todas as tabelas

Revision ID: 6d98036a0373
Revises: 
Create Date: 2026-05-25 21:34:54.430184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d98036a0373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labirinto',
    sa.Column('id_labirinto', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo_labirinto', postgresql.ENUM('4X4', '8X8', '16X16', name='enum_labirinto'), nullable=False),
    sa.PrimaryKeyConstraint('id_labirinto')
    )
    op.create_table('celula',
    sa.Column('id_celula', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('coordenada_x', sa.Integer(), nullable=True),
    sa.Column('coordenada_y', sa.Integer(), nullable=True),
    sa.Column('parede_norte', sa.Boolean(), nullable=True),
    sa.Column('parede_sul', sa.Boolean(), nullable=True),
    sa.Column('parede_leste', sa.Boolean(), nullable=True),
    sa.Column('parede_oeste', sa.Boolean(), nullable=True),
    sa.Column('id_labirinto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_labirinto'], ['labirinto.id_labirinto'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_celula')
    )
    op.create_table('corrida',
    sa.Column('id_corrida', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tempo_total', sa.Integer(), nullable=True),
    sa.Column('tensao_media', sa.Float(), nullable=True),
    sa.Column('corrente_media', sa.Float(), nullable=True),
    sa.Column('velocidade_maxima_percurso', sa.Float(), nullable=True),
    sa.Column('velocidade_media', sa.Float(), nullable=True),
    sa.Column('status_corrida', postgresql.ENUM('EM ANDAMENTO', 'CONCLUIDA', 'ABORTADA', name='enum_status_corrida'), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_labirinto', sa.Integer(), nullable=True),
    sa.Column('desafio_cumprido', sa.Boolean(), nullable=True),
    sa.Column('sessao_hardware_id', sa.Integer(), nullable=True),
    sa.Column('tentativa', sa.Integer(), nullable=True),
    sa.Column('bateria_inicial', sa.Integer(), nullable=True),
    sa.Column('bateria_final', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_labirinto'], ['labirinto.id_labirinto'], ),
    sa.PrimaryKeyConstraint('id_corrida')
    )
    op.create_table('conexao_celula',
    sa.Column('id_celula1', sa.Integer(), nullable=False),
    sa.Column('id_celula2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_celula1'], ['celula.id_celula'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_celula2'], ['celula.id_celula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_celula1', 'id_celula2')
    )
    op.create_table('evento',
    sa.Column('id_evento', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('id_corrida', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_corrida'], ['corrida.id_corrida'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('percurso',
    sa.Column('id_percurso', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id_celula', sa.Integer(), nullable=True),
    sa.Column('id_corrida', sa.Integer(), nullable=True),
    sa.Column('data_hora_passagem', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_celula'], ['celula.id_celula'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_corrida'], ['corrida.id_corrida'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_percurso')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('percurso')
    op.drop_table('evento')
    op.drop_table('conexao_celula')
    op.drop_table('corrida')
    op.drop_table('celula')
    op.drop_table('labirinto')
    # ### end Alembic commands ###
