"""Add telemetry fields to Corrida

Revision ID: 74d69c648eb5
Revises: 4b2c47ad3189
Create Date: 2026-05-16 14:31:54.925950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74d69c648eb5'
down_revision: Union[str, Sequence[str], None] = '4b2c47ad3189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrida', sa.Column('sessao_hardware_id', sa.Integer(), nullable=True))
    op.add_column('corrida', sa.Column('tentativa', sa.Integer(), nullable=True))
    op.add_column('corrida', sa.Column('bateria_inicial', sa.Integer(), nullable=True))
    op.add_column('corrida', sa.Column('bateria_final', sa.Integer(), nullable=True))
    op.alter_column('corrida', 'tensao_media',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('corrida', 'corrente_media',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('corrida', 'velocidade_maxima_percurso',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('corrida', 'velocidade_media',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corrida', 'velocidade_media',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('corrida', 'velocidade_maxima_percurso',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('corrida', 'corrente_media',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('corrida', 'tensao_media',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('corrida', 'bateria_final')
    op.drop_column('corrida', 'bateria_inicial')
    op.drop_column('corrida', 'tentativa')
    op.drop_column('corrida', 'sessao_hardware_id')
    # ### end Alembic commands ###
