"""add_tipo_percurso

Revision ID: 7e99036a0374
Revises: 6d98036a0373
Create Date: 2026-05-30 21:14:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e99036a0374'
down_revision: Union[str, Sequence[str], None] = '6d98036a0373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('percurso', sa.Column('tipo_percurso', sa.String(length=20), server_default='exploratorio', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('percurso', 'tipo_percurso')
    # ### end Alembic commands ###
